//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json;

namespace TradeService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradeRecord
    {
        [JsonIgnore]
        public int Key { get; set; }
        public int Id { get; set; }
        [JsonIgnore]
        public string FileName { get; set; }
        public int Account { get; set; }
        public double Volume { get; set; }
        public string Comment { get; set; }
        [JsonIgnore]
        public int Version { get; set; }
        [JsonIgnore]
        public string Type { get; set; }
    }
}
